In [1]:
print('hello')

hello


In [2]:
pip install numpy pandas

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.3 MB 17.9 MB/s eta 0:00:01
   ---------------------------------------  12.1/12.3 MB 40.6 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 33.0 MB/s  0:00:00
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---------------------------------------- 11.0/11.0 MB 58.5 MB/s  0:00:00

   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]
   ---------------------------------------- 0/4 [pytz]


In [2]:
# numpy - list in python, but it is fast and static.

#[]
l = []
l.append(1)
print(l[0])
l.append(2)
for i in l:
    print(i)


l.extend([3,4,5,6,7])
print(l)
l = l * 10000
for i in range(len(l)):
    l[i] = l[i] * 10000
print(l)    



1
1
2
[1, 2, 3, 4, 5, 6, 7]
[10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 10000, 20000, 30000, 40000, 50000, 60000

In [3]:
import numpy as np
np_list = np.array([1,2,3,4,5])
print(np_list)
np_list = np_list * 10000
print(np_list)

[1 2 3 4 5]
[10000 20000 30000 40000 50000]


In [4]:
print(np_list.sum())
print(np_list.mean())
print(np_list.max())
print(np_list.min())

150000
30000.0
50000
10000


In [6]:
# select * from users where age > 20;
import numpy as np
print(np_list[np_list>np_list.mean()])

np_zeros = np.zeros(6)
np_ones = np.ones(10)
np_numbers = np.arange(0, 100, 1)
print(np_zeros)
print(np_ones)
print(np_numbers)

[40000 50000]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [13]:
l1 = [[0, 0, 0], [1,1,1]]
lt = [['Name','Age','Year'],['Serhan',47,2026]]
for i in range(len(lt)):
    for t in range(len(lt[i])):
        print(lt[i][t], end=' ')
    print()


Name Age Year 
Serhan 47 2026 


In [20]:
arr_2d = np.array([[1,2,3], [4,5,6]])
print(arr_2d)
arr_2d = arr_2d * 2
print(arr_2d)

np.zeros((2,3))


random_2d = np.random.randint(1,100, size=(3,4))
random_1d = np.random.randint(1,100, 6)
print(random_2d)
print(random_1d)

[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[22 14  5 81]
 [87 33 55  6]
 [55 97 61 54]]
[60 45 43  5 84 96]


In [23]:
print(random_2d[0][3])
print(random_2d[0, 3])

81
81


1. Create array: [1200, 1800, 950, 2200, 2500, 3100, 2800]
2. Calculate total weekly sales
3. Find the average daily sales
4. Find days with above-average sales
5. Calculate percentage growth from day 1 to day 7


You have quarterly sales data for 4 products:

           Q1    Q2    Q3    Q4
Product A: 1500, 1800, 2100, 2400
Product B: 900,  1100, 1000, 1200
Product C: 2000, 2200, 1900, 2500
Product 😧 1200, 1300, 1400, 1100

Tasks:
1. Create the 2D array
2. Calculate total annual sales per product
3. Find the best quarter for each product
4. Calculate average quarterly sales across all products
5. Find which product had the highest single-quarter sales
6. Get all sales figures above 2000
