In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np
import pandas as pd

filepath = r'C:\Users\serha\OneDrive\Desktop\Data_Science_New_Era\Data_Science_New_Era\dataset.csv'
df = pd.read_csv(filepath, parse_dates=['Order Date','Ship Date']).reset_index()
df

index                        Region                           Country  \
0         0            Sub-Saharan Africa                              Chad   
1         1                        Europe                            Latvia   
2         2  Middle East and North Africa                          Pakistan   
3         3            Sub-Saharan Africa  Democratic Republic of the Congo   
4         4                        Europe                    Czech Republic   
...     ...                           ...                               ...   
9995   9995                          Asia                              Laos   
9996   9996                        Europe                     Liechtenstein   
9997   9997            Sub-Saharan Africa  Democratic Republic of the Congo   
9998   9998            Sub-Saharan Africa                      South Africa   
9999   9999                          Asia                          Mongolia   

            Item Type Sales Channel Order Priority Order Date   Order ID  \
0     Office Supplies        Online              L 2011-01-27  292494523   
1           Beverages        Online              C 2015-12-28  361825549   
2          Vegetables       Offline              C 2011-01-13  141515767   
3           Household        Online              C 2012-09-11  500364005   
4           Beverages        Online              C 2015-10-27  127481591   
...               ...           ...            ...        ...        ...   
9995        Beverages        Online              H 2014-07-15  199342048   
9996        Cosmetics        Online              C 2012-10-27  763044106   
9997       Vegetables       Offline              M 2013-02-14  848579967   
9998             Meat        Online              L 2017-02-19  298185956   
9999           Snacks       Offline              M 2016-04-12  824410903   

      Ship Date  Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
0    2011-02-12        4484      651.21     524.96     2920025.64  2353920.64   
1    2016-01-23        1075       47.45      31.79       51008.75    34174.25   
2    2011-02-01        6515      154.06      90.93     1003700.90   592408.95   
3    2012-10-06        7683      668.27     502.54     5134318.41  3861014.82   
4    2015-12-05        3491       47.45      31.79      165647.95   110978.89   
...         ...         ...         ...        ...            ...         ...   
9995 2014-07-31        8597       47.45      31.79      407927.65   273298.63   
9996 2012-11-01         562      437.20     263.33      245706.40   147991.46   
9997 2013-03-20        2524      154.06      90.93      388847.44   229507.32   
9998 2017-02-22        8706      421.89     364.69     3672974.34  3174991.14   
9999 2016-04-16         361      152.58      97.44       55081.38    35175.84   

      Total Profit  
0        566105.00  
1         16834.50  
2        411291.95  
3       1273303.59  
4         54669.06  
...            ...  
9995     134629.02  
9996      97714.94  
9997     159340.12  
9998     497983.20  
9999      19905.54  

[10000 rows x 15 columns]

In [8]:
df_unitsold = df['Units Sold']
print(type(df_unitsold))
# for item in dir(df_unitsold):
#     print(item)

units_sold = df_unitsold.to_numpy(dtype=int)
print(units_sold)

<class 'pandas.Series'>
[4484 1075 6515 ... 2524 8706  361]


In [16]:
df_unit_sold = df['Units Sold'].to_numpy(dtype=float)
df_unit_price = df['Unit Price'].to_numpy(dtype=float)
df_unit_cost = df['Unit Cost'].to_numpy(dtype=float)
df_total_cost = df['Total Cost'].to_numpy(dtype=float)
df_total_revenue = df['Total Revenue'].to_numpy(dtype=float)
df_total_profit = df['Total Profit'].to_numpy(dtype=float)









In [17]:
# select total_profit/units_sold as profit_per_unit from dataset where units_sold > 0


df_calc1 = np.divide(df_total_profit,df_unit_sold,out=np.full_like(df_total_profit, np.nan), where=df_unit_sold!=0)
df_calc1

array([126.25,  15.66,  63.13, ...,  63.13,  57.2 ,  55.14],
      shape=(10000,))

In [18]:
# select total_profit/total_revenu as profit_margin where total_rev > 0

df_calc2 = np.divide(df_total_profit,df_total_revenue, out=np.full_like(df_total_profit, np.nan), where=df_total_revenue!=0)
df_calc2

array([0.19386987, 0.33003161, 0.40977541, ..., 0.40977541, 0.13558036,
       0.36138419], shape=(10000,))

In [20]:
# select (unit_rpie - unit_cost) / unit_price as ration where unit_priec > 0
df_calc3 = np.divide(np.subtract(df_unit_price,df_unit_cost),df_unit_cost, out=np.full_like(df_unit_price,np.nan), where=df_unit_price!=0)
df_calc3

array([0.24049451, 0.49260774, 0.69427032, ..., 0.69427032, 0.15684554,
       0.5658867 ], shape=(10000,))

In [34]:
# profit per unit, profit margin, ratio
df['profit per unit'] = df_calc1
df['profit margin'] = df_calc2
df['ratio'] = df_calc3

df_limited = df[['Units Sold','Unit Price','Unit Cost','Total Revenue','Total Cost','Total Profit','profit per unit','profit margin','ratio']]
df_limited.info()




<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Units Sold       10000 non-null  int64  
 1   Unit Price       10000 non-null  float64
 2   Unit Cost        10000 non-null  float64
 3   Total Revenue    10000 non-null  float64
 4   Total Cost       10000 non-null  float64
 5   Total Profit     10000 non-null  float64
 6   profit per unit  10000 non-null  float64
 7   profit margin    10000 non-null  float64
 8   ratio            10000 non-null  float64
dtypes: float64(8), int64(1)
memory usage: 703.3 KB


In [33]:
# select percentile_count(0.75) within group (order by total_profit) from dataaset.
counter = 10



profit_75 = np.nanpercentile(df_total_profit, 75)
revenue_median = np.nanpercentile(df_total_revenue, 50)
unit_80 = np.nanpercentile(df_unit_sold, 80)

mask = (
    (df_total_profit >= profit_75) &
    (df_total_revenue >= revenue_median) &
    (units_sold>=unit_80)
)

# select * from dataset wehre total_proft >= [75th]and total_Rev>50
df['new_col'] = np.where(
    mask, 'high', 'standard'
)

df_filtered =  df.loc[df['new_col'] == 'high']
df_filtered


index                        Region                 Country   Item Type  \
11       11                        Europe  Bosnia and Herzegovina   Baby Food   
14       14  Middle East and North Africa                 Algeria     Clothes   
33       33                        Europe              San Marino  Vegetables   
40       40                        Europe                   Italy      Cereal   
42       42  Middle East and North Africa                  Turkey     Clothes   
...     ...                           ...                     ...         ...   
9958   9958  Middle East and North Africa                 Lebanon   Household   
9962   9962                        Europe                Bulgaria   Cosmetics   
9977   9977                 North America                  Canada   Cosmetics   
9981   9981                          Asia              Kazakhstan     Clothes   
9986   9986                        Europe                  Greece  Vegetables   

     Sales Channel Order Priority Order Date   Order ID  Ship Date  \
11         Offline              M 2012-10-20  479823005 2012-11-15   
14         Offline              C 2011-06-21  181401288 2011-07-21   
33          Online              H 2015-07-05  603977954 2015-07-29   
40         Offline              H 2013-03-10  637702119 2013-04-04   
42          Online              L 2015-02-11  912333714 2015-03-02   
...            ...            ...        ...        ...        ...   
9958        Online              H 2012-01-02  353100430 2012-02-12   
9962        Online              L 2012-07-26  216981542 2012-07-28   
9977       Offline              C 2014-09-23  457183444 2014-10-12   
9981        Online              L 2012-03-15  691468608 2012-04-25   
9986       Offline              H 2010-06-06  694237935 2010-06-26   

      Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
11          9145      255.28     159.42     2334535.60  1457895.90   
14          9527      109.28      35.84     1041110.56   341447.68   
33          9353      154.06      90.93     1440923.18   850468.29   
40          9083      205.70     117.11     1868373.10  1063710.13   
42          8675      109.28      35.84      948004.00   310912.00   
...          ...         ...        ...            ...         ...   
9958        9119      668.27     502.54     6093954.13  4582662.26   
9962        8515      437.20     263.33     3722758.00  2242254.95   
9977        9596      437.20     263.33     4195371.20  2526914.68   
9981        9782      109.28      35.84     1068976.96   350586.88   
9986        9287      154.06      90.93     1430755.22   844466.91   

      Total Profit  profit per unit  profit margin     ratio new_col  
11       876639.70            95.86       0.375509  0.601305    high  
14       699662.88            73.44       0.672035  2.049107    high  
33       590454.89            63.13       0.409775  0.694270    high  
40       804662.97            88.59       0.430676  0.756468    high  
42       637092.00            73.44       0.672035  2.049107    high  
...            ...              ...            ...       ...     ...  
9958    1511291.87           165.73       0.247999  0.329785    high  
9962    1480503.05           173.87       0.397690  0.660274    high  
9977    1668456.52           173.87       0.397690  0.660274    high  
9981     718390.08            73.44       0.672035  2.049107    high  
9986     586288.31            63.13       0.409775  0.694270    high  

[1086 rows x 19 columns]

(case
    when [total_profit] > 10000 
end) 
# case when .. then '' when .. then '' else '' end

In [36]:
conditions = [
    (df_total_profit >= profit_75) & (df_unit_sold >- unit_80),
    (df_total_profit >= np.nanpercentile(df_total_profit, 50)) & (df_unit_sold >= np.nanpercentile(df_unit_sold, 70)),
]
results = ['premium', 'gold']
df['tier'] = np.select(conditions, results, default='standard')
print(df[['Total Profit','tier']])

      Total Profit      tier
0        566105.00  standard
1         16834.50  standard
2        411291.95  standard
3       1273303.59   premium
4         54669.06  standard
...            ...       ...
9995     134629.02  standard
9996      97714.94  standard
9997     159340.12  standard
9998     497983.20      gold
9999      19905.54  standard

[10000 rows x 2 columns]
