In [1]:
import numpy as np
import pandas as pd

In [9]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(arr.sum(axis=1)) # row sums
print(arr.sum(axis=0)) # column sums

print(arr.max(axis=1)) # ?
print(arr.max(axis=0))

print(arr.mean(axis=1).astype(int)) # 2.0,5,8
print(arr.mean(axis=0).astype(int)) # 4,5,6 

[ 6 15 24]
[12 15 18]
[3 6 9]
[7 8 9]
[2 5 8]
[4 5 6]


In [40]:
import pandas as pd
filepathname = r'C:\Users\serha\Data_Science_New_Era\Data_Science_New_Era\sales_fact_sample.csv'
salescsv = pd.read_csv(filepathname)
# print(salescsv.head())
# print(salescsv.tail())

# SELECT Orderid, Quantity FROM salescsv

Columns =salescsv.columns
print(Columns)
salescsv['OrderID']
# salescsv(Columns)

Index(['OrderID', 'OrderDate', 'Customer', 'Region', 'Product', 'SalesChannel',
       'Quantity', 'Revenue', 'Cost'],
      dtype='object')


0     1001
1     1002
2     1003
3     1004
4     1005
5     1006
6     1007
7     1008
8     1009
9     1010
10    1011
11    1012
12    1013
13    1014
14    1015
15    1016
16    1017
17    1018
Name: OrderID, dtype: int64

In [41]:
salescsv.iloc[0]

print(salescsv[salescsv['Customer'] == 'Initech']) # select * from salescsv where customer='initech'

print(salescsv[salescsv['Cost'] > 1000])

    OrderID  OrderDate Customer Region   Product SalesChannel  Quantity  \
2      1003   1/6/2024  Initech  North  Widget A       Retail        15   
4      1005   1/8/2024  Initech  South  Widget C       Online         3   
7      1008   1/9/2024  Initech  South  Widget B       Retail         8   
12     1013  1/14/2024  Initech  South  Widget A       Online        11   
17     1018  3/14/2024  Initech  South  Widget A       Online        11   

    Revenue  Cost  
2      5800  1500  
4       900   600  
7      2400  1600  
12     2750  1980  
17     2750  1980  
    OrderID  OrderDate       Customer Region   Product SalesChannel  Quantity  \
0      1001   1/5/2024      Acme Corp   East  Widget A       Online        10   
2      1003   1/6/2024        Initech  North  Widget A       Retail        15   
3      1004   1/7/2024     Globex Inc   West  Widget A       Retail         7   
7      1008   1/9/2024        Initech  South  Widget B       Retail         8   
8      1009  1/10/2024  

In [43]:
salescsv['discount_cost'] = salescsv['Cost'] * 0.9
salescsv['new_column'] = 'test'
salescsv['new_column1'] = [i for i in range(18)]
print(salescsv)

    OrderID  OrderDate       Customer Region   Product SalesChannel  Quantity  \
0      1001   1/5/2024      Acme Corp   East  Widget A       Online        10   
1      1002   1/6/2024      Acme Corp   East  Widget B       Online         5   
2      1003   1/6/2024        Initech  North  Widget A       Retail        15   
3      1004   1/7/2024     Globex Inc   West  Widget A       Retail         7   
4      1005   1/8/2024        Initech  South  Widget C       Online         3   
5      1006   1/8/2024  Umbrella Corp   East  Widget D       Online         5   
6      1007   1/8/2024  Umbrella Corp  South  Widget C       Online         6   
7      1008   1/9/2024        Initech  South  Widget B       Retail         8   
8      1009  1/10/2024  Umbrella Corp  North  Widget A       Online        12   
9      1010  1/11/2024     Globex Inc   West  Widget C       Retail         4   
10     1011  1/12/2024      Acme Corp   East  Widget A       Retail         6   
11     1012  1/13/2024  Umbr

In [46]:
salescsv[(salescsv['SalesChannel'] == 'Online') & (salescsv['Quantity'] > 2)]

OrderID  OrderDate       Customer Region   Product SalesChannel  Quantity  \
0      1001   1/5/2024      Acme Corp   East  Widget A       Online        10   
1      1002   1/6/2024      Acme Corp   East  Widget B       Online         5   
4      1005   1/8/2024        Initech  South  Widget C       Online         3   
5      1006   1/8/2024  Umbrella Corp   East  Widget D       Online         5   
6      1007   1/8/2024  Umbrella Corp  South  Widget C       Online         6   
8      1009  1/10/2024  Umbrella Corp  North  Widget A       Online        12   
11     1012  1/13/2024  Umbrella Corp  North  Widget B       Online         9   
12     1013  1/14/2024        Initech  South  Widget A       Online        11   
13     1014  2/10/2024  Umbrella Corp  North  Widget A       Online        12   
16     1017  3/13/2024  Umbrella Corp  North  Widget B       Online         9   
17     1018  3/14/2024        Initech  South  Widget A       Online        11   

    Revenue  Cost  discount_cost new_column  new_column1  
0      2500  1800         1620.0       test            0  
1      1500   900          810.0       test            1  
4       900   600          540.0       test            4  
5      1100   800          720.0       test            5  
6      1200   900          810.0       test            6  
8      3000  2160         1944.0       test            8  
11     2700  1890         1701.0       test           11  
12     2750  1980         1782.0       test           12  
13     3000  2160         1944.0       test           13  
16     2700  1890         1701.0       test           16  
17     2750  1980         1782.0       test           17

In [49]:
salescsv['OrderDate'] = pd.to_datetime(salescsv['OrderDate'])
salescsv =salescsv.sort_values('OrderDate', ascending=True)
salescsv[(salescsv['SalesChannel'] == 'Online') & (salescsv['Quantity'] > 2)].groupby('OrderDate').agg({
    'Revenue': 'sum'
})
# sum revenue, group by month/year



Revenue
OrderDate          
2024-01-05     2500
2024-01-06     1500
2024-01-08     3200
2024-01-10     3000
2024-01-13     2700
2024-01-14     2750
2024-02-10     3000
2024-03-13     2700
2024-03-14     2750